/**
 * ReMoDeL (Reusable Model Design Languages) tools for developing
 * and compiling metamodels, models and model transformations.
 *
 * Copyright (c) 2020-2022 Anthony J H Simons
 * University of Sheffield, UK.  All rights reserved.
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This software is proprietary software, whose IP is owned by
 * Anthony J H Simons and the University of Sheffield.  All use of
 * this software must be covered by a license drawn up with the
 * owners.
 *
 * Please contact the Department of Computer Science, University of
 * Sheffield, Regent Court, 211 Portobello, Sheffield S1 4DP, UK or
 * visit www.sheffield.ac.uk/dcs if you need additional information
 * or have any questions.
 */

package meta.graph;

/**
 * Requires remodel.util.Top as the standard root class
 */
import remodel.util.*;

/**
 * Edge is derived from the ReMoDeL concept Graph_Edge.
 * Generated by ReMoDeL on Tue Apr 04 03:26:37 BST 2023.
 * 
 * @author ReMoDeL by Anthony J H Simons
 * @version 3.1
 */
public class Edge extends Top {

   /**
    * Field source is derived from the reference source.
    */
   protected Vertex source;

   /**
    * Method getSource() is derived from the reference source.
    */
   public Vertex getSource() {
      return source;
   }

   /**
    * Method setSource() is derived from the reference source.
    */
   public Edge setSource(Vertex source) {
      this.source = source;
      return this;
   }

   /**
    * Field target is derived from the reference target.
    */
   protected Vertex target;

   /**
    * Method getTarget() is derived from the reference target.
    */
   public Vertex getTarget() {
      return target;
   }

   /**
    * Method setTarget() is derived from the reference target.
    */
   public Edge setTarget(Vertex target) {
      this.target = target;
      return this;
   }

   /**
    * Default constructor Edge() is derived from the concept Edge.
    */
   public Edge() {
   }

}
