/**
 * ReMoDeL (Reusable Model Design Languages) tools for developing
 * and compiling metamodels, models and model transformations.
 *
 * Copyright (c) 2020-2022 Anthony J H Simons
 * University of Sheffield, UK.  All rights reserved.
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This software is proprietary software, whose IP is owned by
 * Anthony J H Simons and the University of Sheffield.  All use of
 * this software must be covered by a license drawn up with the
 * owners.
 *
 * Please contact the Department of Computer Science, University of
 * Sheffield, Regent Court, 211 Portobello, Sheffield S1 4DP, UK or
 * visit www.sheffield.ac.uk/dcs if you need additional information
 * or have any questions.
 */

package meta.umlcd;


/**
 * EndRole is derived from the ReMoDeL concept UmlCd_EndRole.
 * Generated by ReMoDeL on Tue Nov 01 14:39:19 GMT 2022.
 * 
 * @author ReMoDeL by Anthony J H Simons
 * @version 3.1
 */
public class EndRole extends Typed {

   /**
    * Redefined method getType() is derived from the reference type.
    */
   @Override
   public ClassType getType() {
      return (ClassType) type;
   }

   /**
    * Field range is derived from the attribute range.
    */
   protected String range = "";

   /**
    * Method getRange() is derived from the attribute range.
    */
   public String getRange() {
      return range;
   }

   /**
    * Method setRange() is derived from the attribute range.
    */
   public EndRole setRange(String range) {
      this.range = range;
      return this;
   }

   /**
    * Method isOne() is derived from the operation isOne.
    */
   public boolean isOne() {
      return range.equals("") || range.equals("1") || range.equals("1..1");
   }

   /**
    * Method isZeroOne() is derived from the operation isZeroOne.
    */
   public boolean isZeroOne() {
      return range.equals("0..1");
   }

   /**
    * Method isZeroMany() is derived from the operation isZeroMany.
    */
   public boolean isZeroMany() {
      return range.equals("*") || range.equals("0..*");
   }

   /**
    * Method isOneMany() is derived from the operation isOneMany.
    */
   public boolean isOneMany() {
      return range.equals("1..*");
   }

   /**
    * Method isMany() is derived from the operation isMany.
    */
   public boolean isMany() {
      return !this.isOne();
   }

   /**
    * Method isOptional() is derived from the operation isOptional.
    */
   public boolean isOptional() {
      return this.isZeroOne() || this.isZeroMany();
   }

   /**
    * Method isMultiple() is derived from the operation isMultiple.
    */
   public boolean isMultiple() {
      return !(this.isOne() || this.isZeroOne());
   }

   /**
    * Method getName() is derived from the operation getName.
    */
   @Override
   public String getName() {
      if (! name.equals("")) 
         return name;
      else 
         return asName(type.getName());
   }

   /**
    * Redefined method setType() is derived from the reference type.
    */
   @Override
   public EndRole setType(Type type) {
      return (EndRole) super.setType(type);
   }

   /**
    * Redefined method setName() is derived from the attribute name.
    */
   @Override
   public EndRole setName(String name) {
      return (EndRole) super.setName(name);
   }

   /**
    * Default constructor EndRole() is derived from the concept EndRole.
    */
   public EndRole() {
   }

}
