/**
 * ReMoDeL (Reusable Model Design Languages) tools for developing
 * and compiling metamodels, models and model transformations.
 *
 * Copyright (c) 2020-2022 Anthony J H Simons
 * University of Sheffield, UK.  All rights reserved.
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This software is proprietary software, whose IP is owned by
 * Anthony J H Simons and the University of Sheffield.  All use of
 * this software must be covered by a license drawn up with the
 * owners.
 *
 * Please contact the Department of Computer Science, University of
 * Sheffield, Regent Court, 211 Portobello, Sheffield S1 4DP, UK or
 * visit www.sheffield.ac.uk/dcs if you need additional information
 * or have any questions.
 */

package meta.umlcd;

/**
 * Requires remodel.util.Top as the standard root class
 */
import remodel.util.*;

/**
 * Named is derived from the ReMoDeL concept UmlCd_Named.
 * Generated by ReMoDeL on Tue Nov 01 14:39:19 GMT 2022.
 * 
 * @author ReMoDeL by Anthony J H Simons
 * @version 3.1
 */
public class Named extends Top {

   /**
    * Field name is derived from the attribute name.
    */
   protected String name = "";

   /**
    * Method getName() is derived from the attribute name.
    */
   public String getName() {
      return name;
   }

   /**
    * Method setName() is derived from the attribute name.
    */
   public Named setName(String name) {
      this.name = name;
      return this;
   }

   /**
    * Default constructor Named() is derived from the concept Named.
    */
   public Named() {
   }

}
