/**
 * ReMoDeL (Reusable Model Design Languages) tools for developing
 * and compiling metamodels, models and model transformations.
 *
 * Copyright (c) 2020-2022 Anthony J H Simons
 * University of Sheffield, UK.  All rights reserved.
 *
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This software is proprietary software, whose IP is owned by
 * Anthony J H Simons and the University of Sheffield.  All use of
 * this software must be covered by a license drawn up with the
 * owners.
 *
 * Please contact the Department of Computer Science, University of
 * Sheffield, Regent Court, 211 Portobello, Sheffield S1 4DP, UK or
 * visit www.sheffield.ac.uk/dcs if you need additional information
 * or have any questions.
 */

package meta.umlcd;


/**
 * Typed is derived from the ReMoDeL concept UmlCd_Typed.
 * Generated by ReMoDeL on Tue Nov 01 14:39:19 GMT 2022.
 * 
 * @author ReMoDeL by Anthony J H Simons
 * @version 3.1
 */
public class Typed extends Named {

   /**
    * Field type is derived from the reference type.
    */
   protected Type type;

   /**
    * Method getType() is derived from the reference type.
    */
   public Type getType() {
      return type;
   }

   /**
    * Method setType() is derived from the reference type.
    */
   public Typed setType(Type type) {
      this.type = type;
      return this;
   }

   /**
    * Redefined method setName() is derived from the attribute name.
    */
   @Override
   public Typed setName(String name) {
      return (Typed) super.setName(name);
   }

   /**
    * Default constructor Typed() is derived from the concept Typed.
    */
   public Typed() {
   }

}
